### ISSUE TITLE
InventorySingleton as singleton

### ISSUE THREAD

**Issue by drewburlingame** [gamosoft/Inventory-WebAPI#1]
what are the tradeoffs with using a Singleton?  what dev costs will it incur?

**Comment by gamosoft** [comment]
Hello Drew, nice to meet you (virtually at least). :-)
I understand some people don’t like that pattern, but as long as the pattern is applied correctly it should be ok.
I just wanted to make sure only one instance was available at any given time (given the multi-threaded nature of the web), to simulate a DB in the backend.
I’m really not following what you mean by dev costs though. Do you mean additional complexity or maintainability?

**Comment by drewburlingame** [comment]
Hello, nice to meet you too.  I believe we were on a hangout together before.

Yes, by dev costs, i mean additional complexity and maintainability and ....    Singleton simplifies access to a single instance, but that simplification is a tradeoff for complexity elsewhere.  When deciding to use a singleton, it should be well understood what that tradeoff is.

**Comment by gamosoft** [comment]
Hm, I guess you refer to testability complexity if accessed directly? Yes, even using the Fakes framework for this could be a more complicated task to unit test the component, since we don't want to "simulate" the behavior of the actual instance, but rather test it instead.
However in this case since the unit test is applied to the actual controller itself it can cover all the cases below (somewhat like accessing it through a service), and the last run I got with code coverage gave me a total 94% of code covered (of course some pieces don't need to be tested):
![code_coverage](https://cloud.githubusercontent.com/assets/9968384/21008654/f34e312c-bd42-11e6-9747-c332b2d35570.png)

**Comment by gamosoft** [comment]
Oh BTW, I don't know if Laura already told you but given how this week there are a couple of mandatory holidays in Spain, my daughters don't have school, so I have to take the time to take care of them (my wife works too), therefore my availability to continue polishing this app may be reduced. :-(
Still, I'll try to get as much done as I can before the tomorrow deadline!!! :-D
