### ISSUE TITLE
ItemType as enum

### ISSUE THREAD

**Issue by drewburlingame** [gamosoft/Inventory-WebAPI#3]
what is the reasoning for making the ItemType an enum?  what implications does that have?

**Comment by gamosoft** [comment]
I just wanted to strongly-type the Type property of the Item, so users could not choose random values, and also make them consistent.
For example, if using strings could be different with values like “TypeA”, “TYPEA”, “typea”, etc…
Now there’s an issue when consuming these enumerations from the client since they’re treated as integers only so an additional level of interpretation needs to be added, but on the other side, if the server-side code is to be used elsewhere it’s a safer approach.
Also I used enum assuming a closed set of options, so they can be defined at design time (only the ones defined).
