### ISSUE TITLE
NotificationManager static SendNotification

### ISSUE THREAD

**Issue by drewburlingame** [gamosoft/Inventory-WebAPI#4]
i noticed you made the SendNotification method static.  what are other designs you could have gone with that could give more flexibility to devs, and improve automated testibility?

**Comment by gamosoft** [comment]
Good question. Given how it’s static testing can indeed be difficult. It can be simulated of course via additional frameworks such as the fantastic Fakes included in VS, but given that in this case the notifications are implemented by means of sending an email they can’t be per-se defined as unit test, but rather integration tests (to make sure emails are received by the recipients).

**Comment by drewburlingame** [comment]
for testing the repository, do we need to make sure a user received emails?  are we testing they receive emails or that the repo raises notifications?

**Comment by gamosoft** [comment]
I actually hadn't though of that yet. A quick look around in blog posts suggests a modification to the SMTP settings in the test configuration file to write messages to a folder, so it can be monitored, which I have committed already so you can check it out.
This should cover the particular unit test case for sending notifications. I was concerned about race conditions when running the tests, but so far haven't encountered any.

Now, for the question if we should be unit testing notifications being sent when an item is expired (for example), I don't think we should strictly, since the 2 components are integrated, and if we "prove" notifications work with the new test, then it should work in any other circumstance.
What I think could be done is to create some other integration tests to cover the use cases as defined in the original requirements.
